name: Snapshot release

on: workflow_dispatch

permissions:
    contents: read
    id-token: write

jobs:
    release:
        uses: koslibs/configs/.github/workflows/npm-snapshot.yml@v1.0.0
        secrets:
            npm_token: ${{ secrets.NPM_TOKEN }}
